# Generated by Django 5.2.4 on 2025-07-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_remove_order_shipping_method_order_coupon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the payment gateway shown to customers.', max_length=100)),
                ('processor', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('cod', 'Cash on Delivery'), ('custom', 'Custom Payment')], max_length=50, unique=True)),
                ('public_key', models.CharField(blank=True, help_text='Public API Key or equivalent.', max_length=255)),
                ('secret_key', models.CharField(blank=True, help_text='Secret API Key or equivalent.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this payment gateway.')),
                ('is_test_mode', models.BooleanField(default=True, help_text='Run this gateway in test/sandbox mode. Uncheck for live transactions.')),
                ('description', models.TextField(blank=True, help_text='Description shown to the customer during checkout.')),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='The unique ID from the payment gateway.', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentgateway')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
