# Generated by Django 5.2.4 on 2025-07-28 06:49

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Inside Dhaka, USA & Canada', max_length=100, unique=True)),
                ('countries', django_countries.fields.CountryField(blank=True, help_text='Select countries for this zone. Leave blank to apply to all countries.', max_length=746, multiple=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shipping Zone',
                'verbose_name_plural': 'Shipping Zones',
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard Delivery, Express Shipping', max_length=100)),
                ('method_type', models.CharField(choices=[('flat_rate', 'Flat Rate'), ('free_shipping', 'Free Shipping'), ('local_pickup', 'Local Pickup')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost for this shipping method. Set to 0 for Free Shipping.', max_digits=10)),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='This rate will only apply if the order total is above this value.', max_digits=12, null=True)),
                ('maximum_order_value', models.DecimalField(blank=True, decimal_places=2, help_text='This rate will only apply if the order total is below this value.', max_digits=12, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional: A short description shown to the customer at checkout.')),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name': 'Shipping Rate',
                'verbose_name_plural': 'Shipping Rates',
                'ordering': ['zone', 'rate'],
            },
        ),
    ]
