# Generated by Django 5.2.4 on 2025-07-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(help_text='Your company or brand name.', max_length=255)),
                ('organization_logo', models.ImageField(help_text='Your official logo.', upload_to='seo/global/')),
                ('organization_url', models.URLField(help_text="Your website's main URL.")),
                ('contact_phone', models.CharField(blank=True, help_text='Your business phone number.', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Your business address.')),
                ('robots_txt_content', models.TextField(blank=True, default='User-agent: *\nDisallow: /admin/\n\nSitemap: /sitemap.xml', help_text='Content for the robots.txt file. Be careful with changes.')),
            ],
            options={
                'verbose_name': 'Global SEO Settings',
                'verbose_name_plural': 'Global SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(help_text='The old URL path. e.g., /old-product-page/', max_length=2000, unique=True)),
                ('target_url', models.CharField(help_text='The new URL path or full URL. e.g., /new-product-page/', max_length=2000)),
                ('redirect_type', models.IntegerField(choices=[(301, '301 - Permanent Redirect'), (302, '302 - Temporary Redirect')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
                'ordering': ['-created_at'],
            },
        ),
    ]
