# Generated by Django 5.2.4 on 2025-07-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cross_sell_products',
            field=models.ManyToManyField(blank=True, help_text='Products to show on the cart page.', related_name='cross_sold_by', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text="Products to show on this product's page.", related_name='related_to', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='upsell_products',
            field=models.ManyToManyField(blank=True, help_text='Products to suggest as alternatives.', related_name='upsold_by', to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Battery Life, Screen Size', max_length=100)),
                ('value', models.CharField(help_text='e.g., 24 hours, 6.1 inches', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'unique_together': {('product', 'name')},
            },
        ),
    ]
