# Generated by Django 5.2.4 on 2025-07-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_attributevalue_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='The canonical URL for this page.'),
        ),
        migrations.AddField(
            model_name='category',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, help_text="Optimal length: 150-160 characters. Leave blank to use the item's description.", max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='no_follow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='category',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing.'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image for social media sharing (e.g., 1200x630px).', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='category',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing.', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text="Optimal length: 50-60 characters. Leave blank to use the item's name.", max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='The canonical URL for this page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='no_follow',
            field=models.BooleanField(default=False, help_text='Ask search engines not to follow links on this page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_index',
            field=models.BooleanField(default=False, help_text='Ask search engines not to index this page.'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.TextField(blank=True, help_text='Description for social media sharing.'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Image for social media sharing (e.g., 1200x630px).', null=True, upload_to='seo/og/'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_title',
            field=models.CharField(blank=True, help_text='Title for social media sharing.', max_length=255),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='color_code',
            field=models.CharField(blank=True, help_text='e.g., #FF5733', max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='change_quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text="Optimal length: 150-160 characters. Leave blank to use the item's description.", max_length=160),
        ),
        migrations.AlterField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text="Optimal length: 50-60 characters. Leave blank to use the item's name.", max_length=60),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Important for Image SEO.', max_length=255),
        ),
    ]
