# Generated by Django 5.2.4 on 2025-07-27 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0004_category_canonical_url_category_focus_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_changes', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='change_quantity',
            field=models.IntegerField(help_text='Positive for adding stock, negative for removing.'),
        ),
    ]
